# Plex Configuration
# LXC 101 — 10.66.1.233

service:
  friendly_name: "Homelab"
  username: "zhivko.d"
  data_dir: "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server"
  libraries:
    - name: "Movies"
      path: "/mnt/Movies"
    - name: "TV"
      path: "/mnt/TV"
