# Immich Configuration
# LXC 106 — 10.66.1.231

service:
  version: "release"
  timezone: "Europe/Sofia"
  media_location: "/mnt/Photos"
  machine_learning: false
  db:
    host: "127.0.0.1"
    name: "immich"
    user: "immich"
    vector_extension: "vectorchord"
  redis:
    host: "127.0.0.1"
